{"nodes":[{"pos":[12,48],"content":"CDaoException Class | Microsoft Docs","needQuote":false,"needEscape":true,"nodes":[{"content":"CDaoException Class | Microsoft Docs","pos":[0,36]}]},{"pos":[777,796],"content":"CDaoException Class","linkify":"CDaoException Class","nodes":[{"content":"CDaoException Class","pos":[0,19]}]},{"content":"Represents an exception condition arising from the MFC database classes based on data access objects (DAO).","pos":[797,904]},{"pos":[913,919],"content":"Syntax","linkify":"Syntax","nodes":[{"content":"Syntax","pos":[0,6]}]},{"pos":[985,992],"content":"Members","linkify":"Members","nodes":[{"content":"Members","pos":[0,7]}]},{"pos":[1002,1021],"content":"Public Constructors","linkify":"Public Constructors","nodes":[{"content":"Public Constructors","pos":[0,19]}]},{"content":"Name","pos":[1028,1032]},{"content":"Description","pos":[1033,1044]},{"pos":[1082,1143],"content":"<bpt id=\"p1\">[</bpt>CDaoException::CDaoException<ept id=\"p1\">](#cdaoexception__cdaoexception)</ept>","source":"[CDaoException::CDaoException](#cdaoexception__cdaoexception)"},{"pos":[1144,1180],"content":"Constructs a <ph id=\"ph1\">`CDaoException`</ph> object.","source":"Constructs a `CDaoException` object."},{"pos":[1191,1205],"content":"Public Methods","linkify":"Public Methods","nodes":[{"content":"Public Methods","pos":[0,14]}]},{"content":"Name","pos":[1212,1216]},{"content":"Description","pos":[1217,1228]},{"pos":[1266,1327],"content":"<bpt id=\"p1\">[</bpt>CDaoException::GetErrorCount<ept id=\"p1\">](#cdaoexception__geterrorcount)</ept>","source":"[CDaoException::GetErrorCount](#cdaoexception__geterrorcount)"},{"content":"Returns the number of errors in the database engine's Errors collection.","pos":[1328,1400]},{"pos":[1405,1464],"content":"<bpt id=\"p1\">[</bpt>CDaoException::GetErrorInfo<ept id=\"p1\">](#cdaoexception__geterrorinfo)</ept>","source":"[CDaoException::GetErrorInfo](#cdaoexception__geterrorinfo)"},{"content":"Returns error information about a particular error object in the Errors collection.","pos":[1465,1548]},{"pos":[1559,1578],"content":"Public Data Members","linkify":"Public Data Members","nodes":[{"content":"Public Data Members","pos":[0,19]}]},{"content":"Name","pos":[1585,1589]},{"content":"Description","pos":[1590,1601]},{"pos":[1639,1702],"content":"<bpt id=\"p1\">[</bpt>CDaoException::m_nAfxDaoError<ept id=\"p1\">](#cdaoexception__m_nafxdaoerror)</ept>","source":"[CDaoException::m_nAfxDaoError](#cdaoexception__m_nafxdaoerror)"},{"content":"Contains an extended error code for any error in the MFC DAO classes.","pos":[1703,1772]},{"pos":[1777,1836],"content":"<bpt id=\"p1\">[</bpt>CDaoException::m_pErrorInfo<ept id=\"p1\">](#cdaoexception__m_perrorinfo)</ept>","source":"[CDaoException::m_pErrorInfo](#cdaoexception__m_perrorinfo)"},{"pos":[1837,1976],"content":"A pointer to a <bpt id=\"p1\">[</bpt>CDaoErrorInfo<ept id=\"p1\">](../../mfc/reference/cdaoerrorinfo-structure.md)</ept> object that contains information about one DAO error object.","source":"A pointer to a [CDaoErrorInfo](../../mfc/reference/cdaoerrorinfo-structure.md) object that contains information about one DAO error object."},{"pos":[1981,2030],"content":"<bpt id=\"p1\">[</bpt>CDaoException::m_scode<ept id=\"p1\">](#cdaoexception__m_scode)</ept>","source":"[CDaoException::m_scode](#cdaoexception__m_scode)"},{"pos":[2031,2100],"content":"The <bpt id=\"p1\">[</bpt>SCODE<ept id=\"p1\">](#cdaoexception__m_scode)</ept> value associated with the error.","source":"The [SCODE](#cdaoexception__m_scode) value associated with the error."},{"pos":[2110,2117],"content":"Remarks","linkify":"Remarks","nodes":[{"content":"Remarks","pos":[0,7]}]},{"content":"The class includes public data members you can use to determine the cause of the exception.","pos":[2121,2212]},{"content":"<ph id=\"ph1\">`CDaoException`</ph> objects are constructed and thrown by member functions of the DAO database classes.","pos":[2213,2312],"source":"`CDaoException` objects are constructed and thrown by member functions of the DAO database classes."},{"pos":[2320,3027],"content":"[!NOTE]\n The DAO database classes are distinct from the MFC database classes based on Open Database Connectivity (ODBC). All DAO database class names have the \"CDao\" prefix. You can still access ODBC data sources with the DAO classes. In general, the MFC classes based on DAO are more capable than the MFC classes based on ODBC; the DAO-based classes can access data, including through ODBC drivers, via their own database engine. The DAO-based classes also support Data Definition Language (DDL) operations, such as adding tables via the classes, without having to call DAO directly. For information on exceptions thrown by the ODBC classes, see [CDBException](../../mfc/reference/cdbexception-class.md).","leadings":["","> "],"nodes":[{"content":" The DAO database classes are distinct from the MFC database classes based on Open Database Connectivity (ODBC). All DAO database class names have the \"CDao\" prefix. You can still access ODBC data sources with the DAO classes. In general, the MFC classes based on DAO are more capable than the MFC classes based on ODBC; the DAO-based classes can access data, including through ODBC drivers, via their own database engine. The DAO-based classes also support Data Definition Language (DDL) operations, such as adding tables via the classes, without having to call DAO directly. For information on exceptions thrown by the ODBC classes, see [CDBException](../../mfc/reference/cdbexception-class.md).","pos":[8,705],"nodes":[{"content":"The DAO database classes are distinct from the MFC database classes based on Open Database Connectivity (ODBC).","pos":[1,112]},{"content":"All DAO database class names have the \"CDao\" prefix.","pos":[113,165]},{"content":"You can still access ODBC data sources with the DAO classes.","pos":[166,226]},{"content":"In general, the MFC classes based on DAO are more capable than the MFC classes based on ODBC; the DAO-based classes can access data, including through ODBC drivers, via their own database engine.","pos":[227,422]},{"content":"The DAO-based classes also support Data Definition Language (DDL) operations, such as adding tables via the classes, without having to call DAO directly.","pos":[423,576]},{"content":"For information on exceptions thrown by the ODBC classes, see <bpt id=\"p1\">[</bpt>CDBException<ept id=\"p1\">](../../mfc/reference/cdbexception-class.md)</ept>.","pos":[577,697],"source":" For information on exceptions thrown by the ODBC classes, see [CDBException](../../mfc/reference/cdbexception-class.md)."}]}]},{"content":"You can access exception objects within the scope of a <bpt id=\"p1\">[</bpt>CATCH<ept id=\"p1\">](../../mfc/reference/exception-processing.md#catch)</ept> expression.","pos":[3034,3159],"source":"You can access exception objects within the scope of a [CATCH](../../mfc/reference/exception-processing.md#catch) expression."},{"content":"You can also throw <ph id=\"ph1\">`CDaoException`</ph> objects from your own code with the <bpt id=\"p1\">[</bpt>AfxThrowDaoException<ept id=\"p1\">](../../mfc/reference/exception-processing.md#afxthrowdaoexception)</ept> global function.","pos":[3160,3336],"source":" You can also throw `CDaoException` objects from your own code with the [AfxThrowDaoException](../../mfc/reference/exception-processing.md#afxthrowdaoexception) global function."},{"content":"In MFC, all DAO errors are expressed as exceptions, of type <ph id=\"ph1\">`CDaoException`</ph>.","pos":[3343,3419],"source":"In MFC, all DAO errors are expressed as exceptions, of type `CDaoException`."},{"content":"When you catch an exception of this type, you can use <ph id=\"ph1\">`CDaoException`</ph> member functions to retrieve information from any DAO error objects stored in the database engine's Errors collection.","pos":[3420,3608],"source":" When you catch an exception of this type, you can use `CDaoException` member functions to retrieve information from any DAO error objects stored in the database engine's Errors collection."},{"content":"As each error occurs, one or more error objects are placed in the Errors collection.","pos":[3609,3693]},{"content":"(Normally the collection contains only one error object; if you are using an ODBC data source, you are more likely to get multiple error objects.) When another DAO operation generates an error, the Errors collection is cleared, and the new error object is placed in the Errors collection.","pos":[3694,3982]},{"content":"DAO operations that do not generate an error have no effect on the Errors collection.","pos":[3983,4068]},{"content":"For DAO error codes, see the file DAOERR.H.","pos":[4075,4118]},{"content":"For related information, see the topic \"Trappable Data Access Errors\" in DAO Help.","pos":[4119,4201]},{"content":"For more information about exception handling in general, or about <ph id=\"ph1\">`CDaoException`</ph> objects, see the articles <bpt id=\"p1\">[</bpt>Exception Handling (MFC)<ept id=\"p1\">](../../mfc/exception-handling-in-mfc.md)</ept> and <bpt id=\"p2\">[</bpt>Exceptions: Database Exceptions<ept id=\"p2\">](../../mfc/exceptions-database-exceptions.md)</ept>.","pos":[4208,4467],"source":"For more information about exception handling in general, or about `CDaoException` objects, see the articles [Exception Handling (MFC)](../../mfc/exception-handling-in-mfc.md) and [Exceptions: Database Exceptions](../../mfc/exceptions-database-exceptions.md)."},{"content":"The second article contains example code that illustrates exception handling in DAO.","pos":[4468,4552]},{"pos":[4561,4582],"content":"Inheritance Hierarchy","linkify":"Inheritance Hierarchy","nodes":[{"content":"Inheritance Hierarchy","pos":[0,21]}]},{"pos":[4586,4633],"content":"<bpt id=\"p1\">[</bpt>CObject<ept id=\"p1\">](../../mfc/reference/cobject-class.md)</ept>","source":"[CObject](../../mfc/reference/cobject-class.md)"},{"pos":[4640,4693],"content":"<bpt id=\"p1\">[</bpt>CException<ept id=\"p1\">](../../mfc/reference/cexception-class.md)</ept>","source":"[CException](../../mfc/reference/cexception-class.md)"},{"pos":[4724,4736],"content":"Requirements","linkify":"Requirements","nodes":[{"content":"Requirements","pos":[0,12]}]},{"pos":[4740,4760],"content":"<bpt id=\"p1\">**</bpt>Header:<ept id=\"p1\">**</ept> afxdao.h","source":"**Header:** afxdao.h"},{"pos":[4770,4843],"content":"<bpt id=\"p1\">&lt;a name=\"cdaoexception__cdaoexception\"&gt;</bpt><ept id=\"p1\">&lt;/a&gt;</ept>  CDaoException::CDaoException","linkify":"<a name=\"cdaoexception__cdaoexception\"></a>  CDaoException::CDaoException","source":"<a name=\"cdaoexception__cdaoexception\"></a>  CDaoException::CDaoException"},{"pos":[4847,4883],"content":"Constructs a <ph id=\"ph1\">`CDaoException`</ph> object.","source":"Constructs a `CDaoException` object."},{"pos":[4925,4932],"content":"Remarks","linkify":"Remarks","nodes":[{"content":"Remarks","pos":[0,7]}]},{"content":"Ordinarily, the framework creates exception objects when its code throws an exception.","pos":[4936,5022]},{"content":"You seldom need to construct an exception object explicitly.","pos":[5023,5083]},{"content":"If you want to throw a <ph id=\"ph1\">`CDaoException`</ph> from your own code, call the global function <bpt id=\"p1\">[</bpt>AfxThrowDaoException<ept id=\"p1\">](../../mfc/reference/exception-processing.md#afxthrowdaoexception)</ept>.","pos":[5084,5257],"source":" If you want to throw a `CDaoException` from your own code, call the global function [AfxThrowDaoException](../../mfc/reference/exception-processing.md#afxthrowdaoexception)."},{"content":"However, you might want to explicitly create an exception object if you are making direct calls to DAO via the DAO interface pointers that MFC classes encapsulate.","pos":[5264,5427]},{"content":"In that case, you might need to retrieve error information from DAO.","pos":[5428,5496]},{"content":"Suppose an error occurs in DAO when you call a DAO method via the DAODatabases interface to a workspace's Databases collection.","pos":[5497,5624]},{"pos":[5636,5673],"content":"To retrieve the DAO error information","linkify":"To retrieve the DAO error information","nodes":[{"content":"To retrieve the DAO error information","pos":[0,37]}]},{"pos":[5683,5718],"content":"Construct a <ph id=\"ph1\">`CDaoException`</ph> object.","source":"Construct a `CDaoException` object."},{"content":"Call the exception object's <bpt id=\"p1\">[</bpt>GetErrorCount<ept id=\"p1\">](#cdaoexception__geterrorcount)</ept> member function to determine how many error objects are in the database engine's Errors collection.","pos":[5728,5902],"source":"Call the exception object's [GetErrorCount](#cdaoexception__geterrorcount) member function to determine how many error objects are in the database engine's Errors collection."},{"content":"(Normally only one, unless you are using an ODBC data source.)","pos":[5903,5965]},{"content":"Call the exception object's <bpt id=\"p1\">[</bpt>GetErrorInfo<ept id=\"p1\">](#cdaoexception__geterrorinfo)</ept> member function to retrieve one specific error object at a time, by index in the collection, via the exception object.","pos":[5975,6166],"source":"Call the exception object's [GetErrorInfo](#cdaoexception__geterrorinfo) member function to retrieve one specific error object at a time, by index in the collection, via the exception object."},{"content":"Think of the exception object as a proxy for one DAO error object.","pos":[6167,6233]},{"content":"Examine the current <bpt id=\"p1\">[</bpt>CDaoErrorInfo<ept id=\"p1\">](../../mfc/reference/cdaoerrorinfo-structure.md)</ept> structure that <ph id=\"ph1\">`GetErrorInfo`</ph> returns in the <bpt id=\"p2\">[</bpt>m_pErrorInfo<ept id=\"p2\">](#cdaoexception__m_perrorinfo)</ept> data member.","pos":[6243,6429],"source":"Examine the current [CDaoErrorInfo](../../mfc/reference/cdaoerrorinfo-structure.md) structure that `GetErrorInfo` returns in the [m_pErrorInfo](#cdaoexception__m_perrorinfo) data member."},{"content":"Its members provide information on the DAO error.","pos":[6430,6479]},{"content":"In the case of an ODBC data source, repeat steps 3 and 4 as needed, for more error objects.","pos":[6489,6580]},{"pos":[6590,6698],"content":"If you constructed the exception object on the heap, delete it with the <bpt id=\"p1\">**</bpt>delete<ept id=\"p1\">**</ept> operator when you finish.","source":"If you constructed the exception object on the heap, delete it with the **delete** operator when you finish."},{"pos":[6705,6867],"content":"For more information about handling errors in the MFC DAO classes, see the article <bpt id=\"p1\">[</bpt>Exceptions: Database Exceptions<ept id=\"p1\">](../../mfc/exceptions-database-exceptions.md)</ept>.","source":"For more information about handling errors in the MFC DAO classes, see the article [Exceptions: Database Exceptions](../../mfc/exceptions-database-exceptions.md)."},{"pos":[6877,6950],"content":"<bpt id=\"p1\">&lt;a name=\"cdaoexception__geterrorcount\"&gt;</bpt><ept id=\"p1\">&lt;/a&gt;</ept>  CDaoException::GetErrorCount","linkify":"<a name=\"cdaoexception__geterrorcount\"></a>  CDaoException::GetErrorCount","source":"<a name=\"cdaoexception__geterrorcount\"></a>  CDaoException::GetErrorCount"},{"content":"Call this member function to retrieve the number of DAO error objects in the database engine's Errors collection.","pos":[6954,7067]},{"pos":[7115,7127],"content":"Return Value","linkify":"Return Value","nodes":[{"content":"Return Value","pos":[0,12]}]},{"content":"The number of DAO error objects in the database engine's Errors collection.","pos":[7131,7206]},{"pos":[7216,7223],"content":"Remarks","linkify":"Remarks","nodes":[{"content":"Remarks","pos":[0,7]}]},{"content":"This information is useful for looping through the Errors collection to retrieve each of the one or more DAO error objects in the collection.","pos":[7227,7368]},{"content":"To retrieve an error object by index or by DAO error number, call the <bpt id=\"p1\">[</bpt>GetErrorInfo<ept id=\"p1\">](#cdaoexception__geterrorinfo)</ept> member function.","pos":[7369,7500],"source":" To retrieve an error object by index or by DAO error number, call the [GetErrorInfo](#cdaoexception__geterrorinfo) member function."},{"pos":[7508,7668],"content":"[!NOTE]\n Normally there is only one error object in the Errors collection. If you are working with an ODBC data source, however, there could be more than one.","leadings":["","> "],"nodes":[{"content":" Normally there is only one error object in the Errors collection. If you are working with an ODBC data source, however, there could be more than one.","pos":[8,158],"nodes":[{"content":"Normally there is only one error object in the Errors collection.","pos":[1,66]},{"content":"If you are working with an ODBC data source, however, there could be more than one.","pos":[67,150]}]}]},{"pos":[7678,7749],"content":"<bpt id=\"p1\">&lt;a name=\"cdaoexception__geterrorinfo\"&gt;</bpt><ept id=\"p1\">&lt;/a&gt;</ept>  CDaoException::GetErrorInfo","linkify":"<a name=\"cdaoexception__geterrorinfo\"></a>  CDaoException::GetErrorInfo","source":"<a name=\"cdaoexception__geterrorinfo\"></a>  CDaoException::GetErrorInfo"},{"content":"Returns error information about a particular error object in the Errors collection.","pos":[7753,7836]},{"pos":[7892,7902],"content":"Parameters","linkify":"Parameters","nodes":[{"content":"Parameters","pos":[0,10]}]},{"content":"The index of the error information in the database engine's Errors collection, for lookup by index.","pos":[7918,8017]},{"pos":[8027,8034],"content":"Remarks","linkify":"Remarks","nodes":[{"content":"Remarks","pos":[0,7]}]},{"content":"Call this member function to obtain the following kinds of information about the exception:","pos":[8038,8129]},{"content":"Error code","pos":[8139,8149]},{"content":"Source","pos":[8159,8165]},{"content":"Description","pos":[8175,8186]},{"content":"Help file","pos":[8196,8205]},{"content":"Help context","pos":[8215,8227]},{"content":"<ph id=\"ph1\">`GetErrorInfo`</ph> stores the information in the exception object's <ph id=\"ph2\">`m_pErrorInfo`</ph> data member.","pos":[8234,8325],"source":"`GetErrorInfo` stores the information in the exception object's `m_pErrorInfo` data member."},{"content":"For a brief description of the information returned, see <bpt id=\"p1\">[</bpt>m_pErrorInfo<ept id=\"p1\">](#cdaoexception__m_perrorinfo)</ept>.","pos":[8326,8428],"source":" For a brief description of the information returned, see [m_pErrorInfo](#cdaoexception__m_perrorinfo)."},{"content":"If you catch an exception of type <ph id=\"ph1\">`CDaoException`</ph> thrown by MFC, the <ph id=\"ph2\">`m_pErrorInfo`</ph> member will already be filled in.","pos":[8429,8546],"source":" If you catch an exception of type `CDaoException` thrown by MFC, the `m_pErrorInfo` member will already be filled in."},{"content":"If you choose to call DAO directly, you must call the exception object's <ph id=\"ph1\">`GetErrorInfo`</ph> member function yourself to fill <ph id=\"ph2\">`m_pErrorInfo`</ph>.","pos":[8547,8683],"source":" If you choose to call DAO directly, you must call the exception object's `GetErrorInfo` member function yourself to fill `m_pErrorInfo`."},{"content":"For a more detailed description, see the <bpt id=\"p1\">[</bpt>CDaoErrorInfo<ept id=\"p1\">](../../mfc/reference/cdaoerrorinfo-structure.md)</ept> structure.","pos":[8684,8799],"source":" For a more detailed description, see the [CDaoErrorInfo](../../mfc/reference/cdaoerrorinfo-structure.md) structure."},{"pos":[8806,8957],"content":"For information about DAO exceptions, and example code, see the article <bpt id=\"p1\">[</bpt>Exceptions: Database Exceptions<ept id=\"p1\">](../../mfc/exceptions-database-exceptions.md)</ept>.","source":"For information about DAO exceptions, and example code, see the article [Exceptions: Database Exceptions](../../mfc/exceptions-database-exceptions.md)."},{"pos":[8967,9042],"content":"<bpt id=\"p1\">&lt;a name=\"cdaoexception__m_nafxdaoerror\"&gt;</bpt><ept id=\"p1\">&lt;/a&gt;</ept>  CDaoException::m_nAfxDaoError","linkify":"<a name=\"cdaoexception__m_nafxdaoerror\"></a>  CDaoException::m_nAfxDaoError","source":"<a name=\"cdaoexception__m_nafxdaoerror\"></a>  CDaoException::m_nAfxDaoError"},{"content":"Contains an MFC extended error code.","pos":[9046,9082]},{"pos":[9092,9099],"content":"Remarks","linkify":"Remarks","nodes":[{"content":"Remarks","pos":[0,7]}]},{"content":"This code is supplied in cases where a specific component of the MFC DAO classes has erred.","pos":[9103,9194]},{"content":"Possible values are:","pos":[9201,9221]},{"content":"<bpt id=\"p1\">**</bpt>NO_AFX_DAO_ERROR<ept id=\"p1\">**</ept> The most recent operation did not result in an MFC extended error.","pos":[9229,9316],"source":"**NO_AFX_DAO_ERROR** The most recent operation did not result in an MFC extended error."},{"content":"However, the operation could have produced other errors from DAO or OLE, so you should check <bpt id=\"p1\">[</bpt>m_pErrorInfo<ept id=\"p1\">](#cdaoexception__m_perrorinfo)</ept> and possibly <bpt id=\"p2\">[</bpt>m_scode<ept id=\"p2\">](#cdaoexception__m_scode)</ept>.","pos":[9317,9503],"source":" However, the operation could have produced other errors from DAO or OLE, so you should check [m_pErrorInfo](#cdaoexception__m_perrorinfo) and possibly [m_scode](#cdaoexception__m_scode)."},{"content":"<bpt id=\"p1\">**</bpt>AFX_DAO_ERROR_ENGINE_INITIALIZATION<ept id=\"p1\">**</ept> MFC could not initialize the Microsoft Jet database engine.","pos":[9511,9610],"source":"**AFX_DAO_ERROR_ENGINE_INITIALIZATION** MFC could not initialize the Microsoft Jet database engine."},{"content":"OLE might have failed to initialize, or it might have been impossible to create an instance of the DAO database engine object.","pos":[9611,9737]},{"content":"These problems usually suggest a bad installation of either DAO or OLE.","pos":[9738,9809]},{"content":"<bpt id=\"p1\">**</bpt>AFX_DAO_ERROR_DFX_BIND<ept id=\"p1\">**</ept> An address used in a DAO record field exchange (DFX) function call does not exist or is invalid (the address was not used to bind data).","pos":[9817,9980],"source":"**AFX_DAO_ERROR_DFX_BIND** An address used in a DAO record field exchange (DFX) function call does not exist or is invalid (the address was not used to bind data)."},{"content":"You might have passed a bad address in a DFX call, or the address might have become invalid between DFX operations.","pos":[9981,10096]},{"pos":[10104,10243],"content":"<bpt id=\"p1\">**</bpt>AFX_DAO_ERROR_OBJECT_NOT_OPEN<ept id=\"p1\">**</ept> You attempted to open a recordset based on a querydef or a tabledef object that was not in an open state.","source":"**AFX_DAO_ERROR_OBJECT_NOT_OPEN** You attempted to open a recordset based on a querydef or a tabledef object that was not in an open state."},{"pos":[10253,10324],"content":"<bpt id=\"p1\">&lt;a name=\"cdaoexception__m_perrorinfo\"&gt;</bpt><ept id=\"p1\">&lt;/a&gt;</ept>  CDaoException::m_pErrorInfo","linkify":"<a name=\"cdaoexception__m_perrorinfo\"></a>  CDaoException::m_pErrorInfo","source":"<a name=\"cdaoexception__m_perrorinfo\"></a>  CDaoException::m_pErrorInfo"},{"pos":[10328,10508],"content":"Contains a pointer to a <ph id=\"ph1\">`CDaoErrorInfo`</ph> structure that provides information on the DAO error object that you last retrieved by calling <bpt id=\"p1\">[</bpt>GetErrorInfo<ept id=\"p1\">](#cdaoexception__geterrorinfo)</ept>.","source":"Contains a pointer to a `CDaoErrorInfo` structure that provides information on the DAO error object that you last retrieved by calling [GetErrorInfo](#cdaoexception__geterrorinfo)."},{"pos":[10518,10525],"content":"Remarks","linkify":"Remarks","nodes":[{"content":"Remarks","pos":[0,7]}]},{"content":"This object contains the following information:","pos":[10529,10576]},{"content":"CDaoErrorInfo member","pos":[10583,10603]},{"content":"Information","pos":[10604,10615]},{"content":"Meaning","pos":[10616,10623]},{"pos":[10691,10707],"content":"<bpt id=\"p1\">**</bpt>m_lErrorCode<ept id=\"p1\">**</ept>","source":"**m_lErrorCode**"},{"content":"Error Code","pos":[10708,10718]},{"content":"The DAO error code","pos":[10719,10737]},{"content":"Source","pos":[10756,10762]},{"content":"The name of the object or application that originally generated the error","pos":[10763,10836]},{"content":"Description","pos":[10860,10871]},{"content":"A descriptive string associated with the error","pos":[10872,10918]},{"content":"Help File","pos":[10939,10948]},{"content":"A path to a Windows Help file in which the user can get information about the problem","pos":[10949,11034]},{"pos":[11039,11057],"content":"<bpt id=\"p1\">**</bpt>m_lHelpContext<ept id=\"p1\">**</ept>","source":"**m_lHelpContext**"},{"content":"Help Context","pos":[11058,11070]},{"content":"The context ID for a topic in the DAO Help file","pos":[11071,11118]},{"pos":[11126,11288],"content":"For full details about the information contained in the <ph id=\"ph1\">`CDaoErrorInfo`</ph> object, see the <bpt id=\"p1\">[</bpt>CDaoErrorInfo<ept id=\"p1\">](../../mfc/reference/cdaoerrorinfo-structure.md)</ept> structure.","source":"For full details about the information contained in the `CDaoErrorInfo` object, see the [CDaoErrorInfo](../../mfc/reference/cdaoerrorinfo-structure.md) structure."},{"pos":[11298,11359],"content":"<bpt id=\"p1\">&lt;a name=\"cdaoexception__m_scode\"&gt;</bpt><ept id=\"p1\">&lt;/a&gt;</ept>  CDaoException::m_scode","linkify":"<a name=\"cdaoexception__m_scode\"></a>  CDaoException::m_scode","source":"<a name=\"cdaoexception__m_scode\"></a>  CDaoException::m_scode"},{"pos":[11363,11421],"content":"Contains a value of type <ph id=\"ph1\">`SCODE`</ph> that describes the error.","source":"Contains a value of type `SCODE` that describes the error."},{"pos":[11431,11438],"content":"Remarks","linkify":"Remarks","nodes":[{"content":"Remarks","pos":[0,7]}]},{"content":"This is an OLE code.","pos":[11442,11462]},{"content":"You will seldom need to use this value because, in almost all cases, more specific MFC or DAO error information is available in the other <ph id=\"ph1\">`CDaoException`</ph> data members.","pos":[11463,11630],"source":" You will seldom need to use this value because, in almost all cases, more specific MFC or DAO error information is available in the other `CDaoException` data members."},{"content":"For information about <ph id=\"ph1\">`SCODE`</ph>, see the topic <bpt id=\"p1\">[</bpt>Structure of OLE Error Codes<ept id=\"p1\">](http://msdn.microsoft.com/library/windows/desktop/ms690088)</ept> in the <ph id=\"ph2\">[!INCLUDE[winSDK](../../atl/includes/winsdk_md.md)]</ph>.","pos":[11637,11832],"source":"For information about `SCODE`, see the topic [Structure of OLE Error Codes](http://msdn.microsoft.com/library/windows/desktop/ms690088) in the [!INCLUDE[winSDK](../../atl/includes/winsdk_md.md)]."},{"content":"The <ph id=\"ph1\">`SCODE`</ph> data type maps to the <ph id=\"ph2\">`HRESULT`</ph> data type.","pos":[11833,11887],"source":" The `SCODE` data type maps to the `HRESULT` data type."},{"pos":[11896,11904],"content":"See Also","linkify":"See Also","nodes":[{"content":"See Also","pos":[0,8]}]},{"content":"<bpt id=\"p1\">[</bpt>CException Class<ept id=\"p1\">](../../mfc/reference/cexception-class.md)</ept><ph id=\"ph1\"> </ph>","pos":[11908,11968],"source":"[CException Class](../../mfc/reference/cexception-class.md) "},{"content":"<bpt id=\"p1\"> [</bpt>Hierarchy Chart<ept id=\"p1\">](../../mfc/hierarchy-chart.md)</ept><ph id=\"ph1\"> </ph>","pos":[11971,12020],"source":" [Hierarchy Chart](../../mfc/hierarchy-chart.md) "},{"content":"<bpt id=\"p1\"> [</bpt>CException Class<ept id=\"p1\">](../../mfc/reference/cexception-class.md)</ept>","pos":[12023,12083],"source":" [CException Class](../../mfc/reference/cexception-class.md)"}],"content":"---\ntitle: \"CDaoException Class | Microsoft Docs\"\nms.custom: \"\"\nms.date: \"11/04/2016\"\nms.reviewer: \"\"\nms.suite: \"\"\nms.technology: \n  - \"devlang-cpp\"\nms.tgt_pltfrm: \"\"\nms.topic: \"reference\"\nf1_keywords: \n  - \"CDaoException\"\ndev_langs: \n  - \"C++\"\nhelpviewer_keywords: \n  - \"errors [C++], DAO\"\n  - \"CDaoException class\"\n  - \"DAO (Data Access Objects), exceptions\"\n  - \"exceptions, in MFC DAO classes\"\n  - \"Errors collection, DAO\"\n  - \"collections, DAO errors\"\nms.assetid: b2b01fa9-7ce2-42a1-842e-40f13dc50da4\ncaps.latest.revision: 24\nauthor: \"mikeblome\"\nms.author: \"mblome\"\nmanager: \"ghogen\"\ntranslation.priority.ht: \n  - \"cs-cz\"\n  - \"de-de\"\n  - \"es-es\"\n  - \"fr-fr\"\n  - \"it-it\"\n  - \"ja-jp\"\n  - \"ko-kr\"\n  - \"pl-pl\"\n  - \"pt-br\"\n  - \"ru-ru\"\n  - \"tr-tr\"\n  - \"zh-cn\"\n  - \"zh-tw\"\n---\n# CDaoException Class\nRepresents an exception condition arising from the MFC database classes based on data access objects (DAO).  \n  \n## Syntax  \n  \n```  \nclass CDaoException : public CException  \n```  \n  \n## Members  \n  \n### Public Constructors  \n  \n|Name|Description|  \n|----------|-----------------|  \n|[CDaoException::CDaoException](#cdaoexception__cdaoexception)|Constructs a `CDaoException` object.|  \n  \n### Public Methods  \n  \n|Name|Description|  \n|----------|-----------------|  \n|[CDaoException::GetErrorCount](#cdaoexception__geterrorcount)|Returns the number of errors in the database engine's Errors collection.|  \n|[CDaoException::GetErrorInfo](#cdaoexception__geterrorinfo)|Returns error information about a particular error object in the Errors collection.|  \n  \n### Public Data Members  \n  \n|Name|Description|  \n|----------|-----------------|  \n|[CDaoException::m_nAfxDaoError](#cdaoexception__m_nafxdaoerror)|Contains an extended error code for any error in the MFC DAO classes.|  \n|[CDaoException::m_pErrorInfo](#cdaoexception__m_perrorinfo)|A pointer to a [CDaoErrorInfo](../../mfc/reference/cdaoerrorinfo-structure.md) object that contains information about one DAO error object.|  \n|[CDaoException::m_scode](#cdaoexception__m_scode)|The [SCODE](#cdaoexception__m_scode) value associated with the error.|  \n  \n## Remarks  \n The class includes public data members you can use to determine the cause of the exception. `CDaoException` objects are constructed and thrown by member functions of the DAO database classes.  \n  \n> [!NOTE]\n>  The DAO database classes are distinct from the MFC database classes based on Open Database Connectivity (ODBC). All DAO database class names have the \"CDao\" prefix. You can still access ODBC data sources with the DAO classes. In general, the MFC classes based on DAO are more capable than the MFC classes based on ODBC; the DAO-based classes can access data, including through ODBC drivers, via their own database engine. The DAO-based classes also support Data Definition Language (DDL) operations, such as adding tables via the classes, without having to call DAO directly. For information on exceptions thrown by the ODBC classes, see [CDBException](../../mfc/reference/cdbexception-class.md).  \n  \n You can access exception objects within the scope of a [CATCH](../../mfc/reference/exception-processing.md#catch) expression. You can also throw `CDaoException` objects from your own code with the [AfxThrowDaoException](../../mfc/reference/exception-processing.md#afxthrowdaoexception) global function.  \n  \n In MFC, all DAO errors are expressed as exceptions, of type `CDaoException`. When you catch an exception of this type, you can use `CDaoException` member functions to retrieve information from any DAO error objects stored in the database engine's Errors collection. As each error occurs, one or more error objects are placed in the Errors collection. (Normally the collection contains only one error object; if you are using an ODBC data source, you are more likely to get multiple error objects.) When another DAO operation generates an error, the Errors collection is cleared, and the new error object is placed in the Errors collection. DAO operations that do not generate an error have no effect on the Errors collection.  \n  \n For DAO error codes, see the file DAOERR.H. For related information, see the topic \"Trappable Data Access Errors\" in DAO Help.  \n  \n For more information about exception handling in general, or about `CDaoException` objects, see the articles [Exception Handling (MFC)](../../mfc/exception-handling-in-mfc.md) and [Exceptions: Database Exceptions](../../mfc/exceptions-database-exceptions.md). The second article contains example code that illustrates exception handling in DAO.  \n  \n## Inheritance Hierarchy  \n [CObject](../../mfc/reference/cobject-class.md)  \n  \n [CException](../../mfc/reference/cexception-class.md)  \n  \n `CDaoException`  \n  \n## Requirements  \n **Header:** afxdao.h  \n  \n##  <a name=\"cdaoexception__cdaoexception\"></a>  CDaoException::CDaoException  \n Constructs a `CDaoException` object.  \n  \n```  \nCDaoException();\n```  \n  \n### Remarks  \n Ordinarily, the framework creates exception objects when its code throws an exception. You seldom need to construct an exception object explicitly. If you want to throw a `CDaoException` from your own code, call the global function [AfxThrowDaoException](../../mfc/reference/exception-processing.md#afxthrowdaoexception).  \n  \n However, you might want to explicitly create an exception object if you are making direct calls to DAO via the DAO interface pointers that MFC classes encapsulate. In that case, you might need to retrieve error information from DAO. Suppose an error occurs in DAO when you call a DAO method via the DAODatabases interface to a workspace's Databases collection.  \n  \n##### To retrieve the DAO error information  \n  \n1.  Construct a `CDaoException` object.  \n  \n2.  Call the exception object's [GetErrorCount](#cdaoexception__geterrorcount) member function to determine how many error objects are in the database engine's Errors collection. (Normally only one, unless you are using an ODBC data source.)  \n  \n3.  Call the exception object's [GetErrorInfo](#cdaoexception__geterrorinfo) member function to retrieve one specific error object at a time, by index in the collection, via the exception object. Think of the exception object as a proxy for one DAO error object.  \n  \n4.  Examine the current [CDaoErrorInfo](../../mfc/reference/cdaoerrorinfo-structure.md) structure that `GetErrorInfo` returns in the [m_pErrorInfo](#cdaoexception__m_perrorinfo) data member. Its members provide information on the DAO error.  \n  \n5.  In the case of an ODBC data source, repeat steps 3 and 4 as needed, for more error objects.  \n  \n6.  If you constructed the exception object on the heap, delete it with the **delete** operator when you finish.  \n  \n For more information about handling errors in the MFC DAO classes, see the article [Exceptions: Database Exceptions](../../mfc/exceptions-database-exceptions.md).  \n  \n##  <a name=\"cdaoexception__geterrorcount\"></a>  CDaoException::GetErrorCount  \n Call this member function to retrieve the number of DAO error objects in the database engine's Errors collection.  \n  \n```  \nshort GetErrorCount();\n```  \n  \n### Return Value  \n The number of DAO error objects in the database engine's Errors collection.  \n  \n### Remarks  \n This information is useful for looping through the Errors collection to retrieve each of the one or more DAO error objects in the collection. To retrieve an error object by index or by DAO error number, call the [GetErrorInfo](#cdaoexception__geterrorinfo) member function.  \n  \n> [!NOTE]\n>  Normally there is only one error object in the Errors collection. If you are working with an ODBC data source, however, there could be more than one.  \n  \n##  <a name=\"cdaoexception__geterrorinfo\"></a>  CDaoException::GetErrorInfo  \n Returns error information about a particular error object in the Errors collection.  \n  \n```  \nvoid GetErrorInfo(int nIndex);\n```  \n  \n### Parameters  \n `nIndex`  \n The index of the error information in the database engine's Errors collection, for lookup by index.  \n  \n### Remarks  \n Call this member function to obtain the following kinds of information about the exception:  \n  \n-   Error code  \n  \n-   Source  \n  \n-   Description  \n  \n-   Help file  \n  \n-   Help context  \n  \n `GetErrorInfo` stores the information in the exception object's `m_pErrorInfo` data member. For a brief description of the information returned, see [m_pErrorInfo](#cdaoexception__m_perrorinfo). If you catch an exception of type `CDaoException` thrown by MFC, the `m_pErrorInfo` member will already be filled in. If you choose to call DAO directly, you must call the exception object's `GetErrorInfo` member function yourself to fill `m_pErrorInfo`. For a more detailed description, see the [CDaoErrorInfo](../../mfc/reference/cdaoerrorinfo-structure.md) structure.  \n  \n For information about DAO exceptions, and example code, see the article [Exceptions: Database Exceptions](../../mfc/exceptions-database-exceptions.md).  \n  \n##  <a name=\"cdaoexception__m_nafxdaoerror\"></a>  CDaoException::m_nAfxDaoError  \n Contains an MFC extended error code.  \n  \n### Remarks  \n This code is supplied in cases where a specific component of the MFC DAO classes has erred.  \n  \n Possible values are:  \n  \n- **NO_AFX_DAO_ERROR** The most recent operation did not result in an MFC extended error. However, the operation could have produced other errors from DAO or OLE, so you should check [m_pErrorInfo](#cdaoexception__m_perrorinfo) and possibly [m_scode](#cdaoexception__m_scode).  \n  \n- **AFX_DAO_ERROR_ENGINE_INITIALIZATION** MFC could not initialize the Microsoft Jet database engine. OLE might have failed to initialize, or it might have been impossible to create an instance of the DAO database engine object. These problems usually suggest a bad installation of either DAO or OLE.  \n  \n- **AFX_DAO_ERROR_DFX_BIND** An address used in a DAO record field exchange (DFX) function call does not exist or is invalid (the address was not used to bind data). You might have passed a bad address in a DFX call, or the address might have become invalid between DFX operations.  \n  \n- **AFX_DAO_ERROR_OBJECT_NOT_OPEN** You attempted to open a recordset based on a querydef or a tabledef object that was not in an open state.  \n  \n##  <a name=\"cdaoexception__m_perrorinfo\"></a>  CDaoException::m_pErrorInfo  \n Contains a pointer to a `CDaoErrorInfo` structure that provides information on the DAO error object that you last retrieved by calling [GetErrorInfo](#cdaoexception__geterrorinfo).  \n  \n### Remarks  \n This object contains the following information:  \n  \n|CDaoErrorInfo member|Information|Meaning|  \n|--------------------------|-----------------|-------------|  \n|**m_lErrorCode**|Error Code|The DAO error code|  \n|`m_strSource`|Source|The name of the object or application that originally generated the error|  \n|`m_strDescription`|Description|A descriptive string associated with the error|  \n|`m_strHelpFile`|Help File|A path to a Windows Help file in which the user can get information about the problem|  \n|**m_lHelpContext**|Help Context|The context ID for a topic in the DAO Help file|  \n  \n For full details about the information contained in the `CDaoErrorInfo` object, see the [CDaoErrorInfo](../../mfc/reference/cdaoerrorinfo-structure.md) structure.  \n  \n##  <a name=\"cdaoexception__m_scode\"></a>  CDaoException::m_scode  \n Contains a value of type `SCODE` that describes the error.  \n  \n### Remarks  \n This is an OLE code. You will seldom need to use this value because, in almost all cases, more specific MFC or DAO error information is available in the other `CDaoException` data members.  \n  \n For information about `SCODE`, see the topic [Structure of OLE Error Codes](http://msdn.microsoft.com/library/windows/desktop/ms690088) in the [!INCLUDE[winSDK](../../atl/includes/winsdk_md.md)]. The `SCODE` data type maps to the `HRESULT` data type.  \n  \n## See Also  \n [CException Class](../../mfc/reference/cexception-class.md)   \n [Hierarchy Chart](../../mfc/hierarchy-chart.md)   \n [CException Class](../../mfc/reference/cexception-class.md)\n"}