{"nodes":[{"pos":[12,56],"content":"Exception Handling Routines | Microsoft Docs","needQuote":false,"needEscape":true,"nodes":[{"content":"Exception Handling Routines | Microsoft Docs","pos":[0,44]}]},{"content":"Exception Handling Routines","pos":[634,661]},{"content":"Use the C++ exception-handling functions to recover from unexpected events during program execution.","pos":[662,762]},{"content":"Exception-Handling Functions","pos":[772,800]},{"content":"Function","pos":[807,815]},{"content":"Use","pos":[816,819]},{"content":".NET Framework equivalent","pos":[820,845]},{"content":"_set_se_translator","pos":[912,930]},{"content":"Handle Win32 exceptions (C structured exceptions) as C++ typed exceptions","pos":[985,1058]},{"content":"Not applicable.","pos":[1059,1074]},{"content":"To call the standard C function, use <ph id=\"ph1\">`PInvoke`</ph>.","pos":[1075,1122],"source":" To call the standard C function, use `PInvoke`."},{"content":"For more information, see <bpt id=\"p1\">[</bpt>Platform Invoke Examples<ept id=\"p1\">](http://msdn.microsoft.com/Library/15926806-f0b7-487e-93a6-4e9367ec689f)</ept>.","pos":[1123,1248],"source":" For more information, see [Platform Invoke Examples](http://msdn.microsoft.com/Library/15926806-f0b7-487e-93a6-4e9367ec689f)."},{"content":"set_terminate","pos":[1254,1267]},{"pos":[1322,1374],"content":"Install your own termination routine to be called by"},{"content":"Not applicable.","pos":[1387,1402]},{"content":"To call the standard C function, use <ph id=\"ph1\">`PInvoke`</ph>.","pos":[1403,1450],"source":" To call the standard C function, use `PInvoke`."},{"content":"For more information, see <bpt id=\"p1\">[</bpt>Platform Invoke Examples<ept id=\"p1\">](http://msdn.microsoft.com/Library/15926806-f0b7-487e-93a6-4e9367ec689f)</ept>.","pos":[1451,1576],"source":" For more information, see [Platform Invoke Examples](http://msdn.microsoft.com/Library/15926806-f0b7-487e-93a6-4e9367ec689f)."},{"content":"set_unexpected","pos":[1582,1596]},{"pos":[1652,1705],"content":"Install your own termination function to be called by"},{"content":"Not applicable.","pos":[1719,1734]},{"content":"To call the standard C function, use <ph id=\"ph1\">`PInvoke`</ph>.","pos":[1735,1782],"source":" To call the standard C function, use `PInvoke`."},{"content":"For more information, see <bpt id=\"p1\">[</bpt>Platform Invoke Examples<ept id=\"p1\">](http://msdn.microsoft.com/Library/15926806-f0b7-487e-93a6-4e9367ec689f)</ept>.","pos":[1783,1908],"source":" For more information, see [Platform Invoke Examples](http://msdn.microsoft.com/Library/15926806-f0b7-487e-93a6-4e9367ec689f)."},{"content":"terminate","pos":[1914,1923]},{"content":"Called automatically under certain circumstances after exception is thrown.","pos":[1974,2049]},{"content":"The <ph id=\"ph1\">`terminate`</ph> function calls <ph id=\"ph2\">`abort`</ph> or a function you specify using","pos":[2050,2120],"source":" The `terminate` function calls `abort` or a function you specify using "},{"content":"Not applicable.","pos":[2137,2152]},{"content":"To call the standard C function, use <ph id=\"ph1\">`PInvoke`</ph>.","pos":[2153,2200],"source":" To call the standard C function, use `PInvoke`."},{"content":"For more information, see <bpt id=\"p1\">[</bpt>Platform Invoke Examples<ept id=\"p1\">](http://msdn.microsoft.com/Library/15926806-f0b7-487e-93a6-4e9367ec689f)</ept>.","pos":[2201,2326],"source":" For more information, see [Platform Invoke Examples](http://msdn.microsoft.com/Library/15926806-f0b7-487e-93a6-4e9367ec689f)."},{"content":"unexpected","pos":[2332,2342]},{"content":"Calls <ph id=\"ph1\">`terminate`</ph> or a function you specify using <ph id=\"ph2\">`set_unexpected`</ph>.","pos":[2394,2461],"source":"Calls `terminate` or a function you specify using `set_unexpected`."},{"content":"The <ph id=\"ph1\">`unexpected`</ph> function is not used in current Microsoft C++ exception-handling implementation","pos":[2462,2558],"source":" The `unexpected` function is not used in current Microsoft C++ exception-handling implementation"},{"content":"System::Exception Class","pos":[2560,2583]},{"content":"See Also","pos":[2658,2666]},{"content":"Run-Time Routines by Category","pos":[2671,2700]}],"content":"---\ntitle: \"Exception Handling Routines | Microsoft Docs\"\nms.custom: \"\"\nms.date: \"11/04/2016\"\nms.reviewer: \"\"\nms.suite: \"\"\nms.technology: \n  - \"devlang-cpp\"\nms.tgt_pltfrm: \"\"\nms.topic: \"article\"\nf1_keywords: \n  - \"c.exceptions\"\ndev_langs: \n  - \"C++\"\n  - \"C\"\nhelpviewer_keywords: \n  - \"exception handling, routines\"\nms.assetid: f60548c6-850a-4e1e-a79b-a2a6a541ab62\ncaps.latest.revision: 8\nauthor: \"corob-msft\"\nms.author: \"corob\"\nmanager: \"ghogen\"\ntranslation.priority.ht: \n  - \"cs-cz\"\n  - \"de-de\"\n  - \"es-es\"\n  - \"fr-fr\"\n  - \"it-it\"\n  - \"ja-jp\"\n  - \"ko-kr\"\n  - \"pl-pl\"\n  - \"pt-br\"\n  - \"ru-ru\"\n  - \"tr-tr\"\n  - \"zh-cn\"\n  - \"zh-tw\"\n---\n# Exception Handling Routines\nUse the C++ exception-handling functions to recover from unexpected events during program execution.  \n  \n### Exception-Handling Functions  \n  \n|Function|Use|.NET Framework equivalent|  \n|--------------|---------|-------------------------------|  \n|[_set_se_translator](../c-runtime-library/reference/set-se-translator.md)|Handle Win32 exceptions (C structured exceptions) as C++ typed exceptions|Not applicable. To call the standard C function, use `PInvoke`. For more information, see [Platform Invoke Examples](http://msdn.microsoft.com/Library/15926806-f0b7-487e-93a6-4e9367ec689f).|  \n|[set_terminate](../c-runtime-library/reference/set-terminate-crt.md)|Install your own termination routine to be called by `terminate`|Not applicable. To call the standard C function, use `PInvoke`. For more information, see [Platform Invoke Examples](http://msdn.microsoft.com/Library/15926806-f0b7-487e-93a6-4e9367ec689f).|  \n|[set_unexpected](../c-runtime-library/reference/set-unexpected-crt.md)|Install your own termination function to be called by `unexpected`|Not applicable. To call the standard C function, use `PInvoke`. For more information, see [Platform Invoke Examples](http://msdn.microsoft.com/Library/15926806-f0b7-487e-93a6-4e9367ec689f).|  \n|[terminate](../c-runtime-library/reference/terminate-crt.md)|Called automatically under certain circumstances after exception is thrown. The `terminate` function calls `abort` or a function you specify using `set_terminate`|Not applicable. To call the standard C function, use `PInvoke`. For more information, see [Platform Invoke Examples](http://msdn.microsoft.com/Library/15926806-f0b7-487e-93a6-4e9367ec689f).|  \n|[unexpected](../c-runtime-library/reference/unexpected-crt.md)|Calls `terminate` or a function you specify using `set_unexpected`. The `unexpected` function is not used in current Microsoft C++ exception-handling implementation|[System::Exception Class](https://msdn.microsoft.com/en-us/library/system.exception.aspx)|  \n  \n## See Also  \n [Run-Time Routines by Category](../c-runtime-library/run-time-routines-by-category.md)"}