{"nodes":[{"pos":[12,49],"content":"Compiler Error C2707 | Microsoft Docs","needQuote":false,"needEscape":true,"nodes":[{"content":"Compiler Error C2707 | Microsoft Docs","pos":[0,37]}]},{"pos":[597,617],"content":"Compiler Error C2707","linkify":"Compiler Error C2707","nodes":[{"content":"Compiler Error C2707","pos":[0,20]}]},{"content":"'identifier' : bad context for intrinsic function","pos":[618,667]},{"content":"Structured exception-handling intrinsics are invalid in certain contexts:","pos":[674,747]},{"pos":[757,824],"content":"<ph id=\"ph1\">`_exception_code()`</ph> outside an exception filter or <ph id=\"ph2\">`__except`</ph> block","source":"`_exception_code()` outside an exception filter or `__except` block"},{"pos":[834,881],"content":"<ph id=\"ph1\">`_exception_info()`</ph> outside an exception filter","source":"`_exception_info()` outside an exception filter"},{"pos":[891,944],"content":"<ph id=\"ph1\">`_abnormal_termination()`</ph> outside a <ph id=\"ph2\">`__finally`</ph> block","source":"`_abnormal_termination()` outside a `__finally` block"},{"content":"To resolve the error, be sure that the exception-handling intrinsics are placed in the appropriate context.","pos":[951,1058]},{"pos":[1067,1074],"content":"Example","linkify":"Example","nodes":[{"content":"Example","pos":[0,7]}]},{"content":"The following sample generates C2707.","pos":[1078,1115]}],"content":"---\ntitle: \"Compiler Error C2707 | Microsoft Docs\"\nms.custom: \"\"\nms.date: \"11/04/2016\"\nms.reviewer: \"\"\nms.suite: \"\"\nms.technology: \n  - \"devlang-cpp\"\nms.tgt_pltfrm: \"\"\nms.topic: \"error-reference\"\nf1_keywords: \n  - \"C2707\"\ndev_langs: \n  - \"C++\"\nhelpviewer_keywords: \n  - \"C2707\"\nms.assetid: 3deaf45c-74da-4c9d-acc6-b82412720b74\ncaps.latest.revision: 9\nauthor: \"corob-msft\"\nms.author: \"corob\"\nmanager: \"ghogen\"\ntranslation.priority.ht: \n  - \"cs-cz\"\n  - \"de-de\"\n  - \"es-es\"\n  - \"fr-fr\"\n  - \"it-it\"\n  - \"ja-jp\"\n  - \"ko-kr\"\n  - \"pl-pl\"\n  - \"pt-br\"\n  - \"ru-ru\"\n  - \"tr-tr\"\n  - \"zh-cn\"\n  - \"zh-tw\"\n---\n# Compiler Error C2707\n'identifier' : bad context for intrinsic function  \n  \n Structured exception-handling intrinsics are invalid in certain contexts:  \n  \n-   `_exception_code()` outside an exception filter or `__except` block  \n  \n-   `_exception_info()` outside an exception filter  \n  \n-   `_abnormal_termination()` outside a `__finally` block  \n  \n To resolve the error, be sure that the exception-handling intrinsics are placed in the appropriate context.  \n  \n## Example  \n The following sample generates C2707.  \n  \n```  \n// C2707.cpp  \n#include <windows.h>  \n#include <stdio.h>  \n  \nLONG MyFilter(LONG excode)   \n{  \n    return (excode == EXCEPTION_ACCESS_VIOLATION ?  \n        EXCEPTION_EXECUTE_HANDLER : EXCEPTION_CONTINUE_SEARCH);   // OK  \n}  \n  \nLONG func(void)   \n{  \n    int x, y;  \n    return(GetExceptionCode() == EXCEPTION_ACCESS_VIOLATION ?  // C2707  \n             EXCEPTION_EXECUTE_HANDLER : EXCEPTION_CONTINUE_SEARCH);  \n  \n    __try   \n    {  \n        y = 0;  \n        x = 4 / y;  \n        return 0;  \n     }  \n  \n    __except(MyFilter(GetExceptionCode()))   \n    {  \n        return(GetExceptionCode() == EXCEPTION_ACCESS_VIOLATION ? // ok  \n               EXCEPTION_EXECUTE_HANDLER : EXCEPTION_CONTINUE_SEARCH);  \n    }  \n}  \n  \nint main()   \n{  \n    __try   \n    {  \n        func();  \n    } __except(EXCEPTION_EXECUTE_HANDLER)  \n    {  \n        printf_s(\"Caught exception\\n\");  \n    }  \n}  \n```"}