{"nodes":[{"pos":[12,50],"content":"_abnormal_termination | Microsoft Docs","needQuote":false,"needEscape":true,"nodes":[{"content":"_abnormal_termination | Microsoft Docs","pos":[0,38]}]},{"content":"_abnormal_termination","pos":[858,879]},{"pos":[880,1064],"content":"Indicates whether the <ph id=\"ph1\">`__finally`</ph> block of a <bpt id=\"p1\">[</bpt>try-finally statement<ept id=\"p1\">](../cpp/try-finally-statement.md)</ept> is entered while the system is executing an internal list of termination handlers.","source":"Indicates whether the `__finally` block of a [try-finally statement](../cpp/try-finally-statement.md) is entered while the system is executing an internal list of termination handlers."},{"content":"Syntax","pos":[1073,1079]},{"content":"Return Value","pos":[1145,1157]},{"pos":[1168,1227],"content":"if the system is <bpt id=\"p1\">*</bpt>unwinding<ept id=\"p1\">*</ept> the stack; otherwise, <ph id=\"ph1\">`false`</ph>.","source":" if the system is *unwinding* the stack; otherwise, `false`."},{"content":"Remarks","pos":[1236,1243]},{"content":"This is an internal function used to manage unwinding exceptions, and is not intended to be called from user code.","pos":[1247,1361]},{"content":"Requirements","pos":[1370,1382]},{"content":"Routine","pos":[1389,1396]},{"content":"Required header","pos":[1397,1412]},{"content":"_abnormal_termination","pos":[1457,1478]},{"content":"excpt.h","pos":[1479,1486]},{"content":"See Also","pos":[1496,1504]},{"content":"try-finally Statement","pos":[1509,1530]}],"content":"---\ntitle: \"_abnormal_termination | Microsoft Docs\"\nms.custom: \"\"\nms.date: \"11/04/2016\"\nms.reviewer: \"\"\nms.suite: \"\"\nms.technology: \n  - \"devlang-cpp\"\nms.tgt_pltfrm: \"\"\nms.topic: \"article\"\napiname: \n  - \"_abnormal_termination\"\napilocation: \n  - \"msvcr110.dll\"\n  - \"msvcr110_clr0400.dll\"\n  - \"msvcr90.dll\"\n  - \"msvcr120.dll\"\n  - \"msvcrt.dll\"\n  - \"msvcr80.dll\"\n  - \"msvcr100.dll\"\napitype: \"DLLExport\"\nf1_keywords: \n  - \"_abnormal_termination\"\ndev_langs: \n  - \"C++\"\nhelpviewer_keywords: \n  - \"_abnormal_termination\"\nms.assetid: 952970a4-9586-4c3d-807a-db729448c91c\ncaps.latest.revision: 2\nauthor: \"corob-msft\"\nms.author: \"corob\"\nmanager: \"ghogen\"\ntranslation.priority.ht: \n  - \"de-de\"\n  - \"es-es\"\n  - \"fr-fr\"\n  - \"it-it\"\n  - \"ja-jp\"\n  - \"ko-kr\"\n  - \"ru-ru\"\n  - \"zh-cn\"\n  - \"zh-tw\"\ntranslation.priority.mt: \n  - \"cs-cz\"\n  - \"pl-pl\"\n  - \"pt-br\"\n  - \"tr-tr\"\n---\n# _abnormal_termination\nIndicates whether the `__finally` block of a [try-finally statement](../cpp/try-finally-statement.md) is entered while the system is executing an internal list of termination handlers.  \n  \n## Syntax  \n  \n```cpp  \nint   _abnormal_termination(  \n   );  \n```  \n  \n## Return Value  \n `true` if the system is *unwinding* the stack; otherwise, `false`.  \n  \n## Remarks  \n This is an internal function used to manage unwinding exceptions, and is not intended to be called from user code.  \n  \n## Requirements  \n  \n|Routine|Required header|  \n|-------------|---------------------|  \n|_abnormal_termination|excpt.h|  \n  \n## See Also  \n [try-finally Statement](../cpp/try-finally-statement.md)"}