{"nodes":[{"pos":[12,48],"content":"CAtlException Class | Microsoft Docs","needQuote":false,"needEscape":true,"nodes":[{"content":"CAtlException Class | Microsoft Docs","pos":[0,36]}]},{"pos":[662,681],"content":"CAtlException Class","linkify":"CAtlException Class","nodes":[{"content":"CAtlException Class","pos":[0,19]}]},{"content":"This class defines an ATL exception.","pos":[682,718]},{"pos":[727,733],"content":"Syntax","linkify":"Syntax","nodes":[{"content":"Syntax","pos":[0,6]}]},{"pos":[775,782],"content":"Members","linkify":"Members","nodes":[{"content":"Members","pos":[0,7]}]},{"pos":[792,811],"content":"Public Constructors","linkify":"Public Constructors","nodes":[{"content":"Public Constructors","pos":[0,19]}]},{"content":"Name","pos":[818,822]},{"content":"Description","pos":[823,834]},{"pos":[872,933],"content":"<bpt id=\"p1\">[</bpt>CAtlException::CAtlException<ept id=\"p1\">](#catlexception__catlexception)</ept>","source":"[CAtlException::CAtlException](#catlexception__catlexception)"},{"content":"The constructor.","pos":[934,950]},{"pos":[961,977],"content":"Public Operators","linkify":"Public Operators","nodes":[{"content":"Public Operators","pos":[0,16]}]},{"content":"Name","pos":[984,988]},{"content":"Description","pos":[989,1000]},{"pos":[1038,1105],"content":"<bpt id=\"p1\">[</bpt>CAtlException::operator HRESULT<ept id=\"p1\">](#catlexception__operator_hresult)</ept>","source":"[CAtlException::operator HRESULT](#catlexception__operator_hresult)"},{"content":"Casts the current object to an HRESULT value.","pos":[1106,1151]},{"pos":[1162,1181],"content":"Public Data Members","linkify":"Public Data Members","nodes":[{"content":"Public Data Members","pos":[0,19]}]},{"content":"Name","pos":[1188,1192]},{"content":"Description","pos":[1193,1204]},{"pos":[1242,1285],"content":"<bpt id=\"p1\">[</bpt>CAtlException::m_hr<ept id=\"p1\">](#catlexception__m_hr)</ept>","source":"[CAtlException::m_hr](#catlexception__m_hr)"},{"content":"The variable of type HRESULT created by the object and used to store the error condition.","pos":[1286,1375]},{"pos":[1385,1392],"content":"Remarks","linkify":"Remarks","nodes":[{"content":"Remarks","pos":[0,7]}]},{"content":"A <ph id=\"ph1\">`CAtlException`</ph> object represents an exception condition related to an ATL operation.","pos":[1396,1483],"source":"A `CAtlException` object represents an exception condition related to an ATL operation."},{"content":"The <ph id=\"ph1\">`CAtlException`</ph> class includes a public data member that stores the status code indicating the reason for the exception and a cast operator that allows you to treat the exception as if it were an HRESULT.","pos":[1484,1692],"source":" The `CAtlException` class includes a public data member that stores the status code indicating the reason for the exception and a cast operator that allows you to treat the exception as if it were an HRESULT."},{"pos":[1699,1791],"content":"In general, you will call <ph id=\"ph1\">`AtlThrow`</ph> rather than creating a <ph id=\"ph2\">`CAtlException`</ph> object directly.","source":"In general, you will call `AtlThrow` rather than creating a `CAtlException` object directly."},{"pos":[1800,1812],"content":"Requirements","linkify":"Requirements","nodes":[{"content":"Requirements","pos":[0,12]}]},{"pos":[1816,1839],"content":"<bpt id=\"p1\">**</bpt>Header:<ept id=\"p1\">**</ept> atlexcept.h","source":"**Header:** atlexcept.h"},{"pos":[1849,1922],"content":"<bpt id=\"p1\">&lt;a name=\"catlexception__catlexception\"&gt;</bpt><ept id=\"p1\">&lt;/a&gt;</ept>  CAtlException::CAtlException","linkify":"<a name=\"catlexception__catlexception\"></a>  CAtlException::CAtlException","source":"<a name=\"catlexception__catlexception\"></a>  CAtlException::CAtlException"},{"content":"The constructor.","pos":[1926,1942]},{"pos":[2025,2035],"content":"Parameters","linkify":"Parameters","nodes":[{"content":"Parameters","pos":[0,10]}]},{"content":"The <ph id=\"ph1\">`HRESULT`</ph> error code.","pos":[2047,2072],"source":" The `HRESULT` error code."},{"pos":[2082,2161],"content":"<bpt id=\"p1\">&lt;a name=\"catlexception__operator_hresult\"&gt;</bpt><ept id=\"p1\">&lt;/a&gt;</ept>  CAtlException::operator HRESULT","linkify":"<a name=\"catlexception__operator_hresult\"></a>  CAtlException::operator HRESULT","source":"<a name=\"catlexception__operator_hresult\"></a>  CAtlException::operator HRESULT"},{"content":"Casts the current object to an HRESULT value.","pos":[2165,2210]},{"content":"```operator HRESULT() const throw ();","pos":[2216,2253]},{"content":"HRESULT m_hr;","pos":[2362,2375]}],"content":"---\ntitle: \"CAtlException Class | Microsoft Docs\"\nms.custom: \"\"\nms.date: \"11/04/2016\"\nms.reviewer: \"\"\nms.suite: \"\"\nms.technology: \n  - \"devlang-cpp\"\nms.tgt_pltfrm: \"\"\nms.topic: \"reference\"\nf1_keywords: \n  - \"CAtlException\"\n  - \"ATL::CAtlException\"\n  - \"ATL.CAtlException\"\ndev_langs: \n  - \"C++\"\nhelpviewer_keywords: \n  - \"CAtlException class\"\nms.assetid: 3fd7b041-f70d-4292-b947-0d70781d95a8\ncaps.latest.revision: 19\nauthor: \"mikeblome\"\nms.author: \"mblome\"\nmanager: \"ghogen\"\ntranslation.priority.ht: \n  - \"cs-cz\"\n  - \"de-de\"\n  - \"es-es\"\n  - \"fr-fr\"\n  - \"it-it\"\n  - \"ja-jp\"\n  - \"ko-kr\"\n  - \"pl-pl\"\n  - \"pt-br\"\n  - \"ru-ru\"\n  - \"tr-tr\"\n  - \"zh-cn\"\n  - \"zh-tw\"\n---\n# CAtlException Class\nThis class defines an ATL exception.  \n  \n## Syntax  \n  \n```\nclass CAtlException\n```  \n  \n## Members  \n  \n### Public Constructors  \n  \n|Name|Description|  \n|----------|-----------------|  \n|[CAtlException::CAtlException](#catlexception__catlexception)|The constructor.|  \n  \n### Public Operators  \n  \n|Name|Description|  \n|----------|-----------------|  \n|[CAtlException::operator HRESULT](#catlexception__operator_hresult)|Casts the current object to an HRESULT value.|  \n  \n### Public Data Members  \n  \n|Name|Description|  \n|----------|-----------------|  \n|[CAtlException::m_hr](#catlexception__m_hr)|The variable of type HRESULT created by the object and used to store the error condition.|  \n  \n## Remarks  \n A `CAtlException` object represents an exception condition related to an ATL operation. The `CAtlException` class includes a public data member that stores the status code indicating the reason for the exception and a cast operator that allows you to treat the exception as if it were an HRESULT.  \n  \n In general, you will call `AtlThrow` rather than creating a `CAtlException` object directly.  \n  \n## Requirements  \n **Header:** atlexcept.h  \n  \n##  <a name=\"catlexception__catlexception\"></a>  CAtlException::CAtlException  \n The constructor.  \n  \n```\nCAtlException(HRESULT hr) throw();\nCAtlException() throw();\n```  \n  \n### Parameters  \n `hr`  \n The `HRESULT` error code.  \n  \n##  <a name=\"catlexception__operator_hresult\"></a>  CAtlException::operator HRESULT  \n Casts the current object to an HRESULT value.  \n  \n```operator HRESULT() const throw ();\n```  \n  \n##  <a name=\"catlexception__m_hr\"></a>  CAtlException::m_hr  \n The `HRESULT` data member.  \n  \n```\nHRESULT m_hr;\n```  \n  \n### Remarks  \n The data member that stores the error condition. The HRESULT value is set by the constructor, [CAtlException::CAtlException](#catlexception__catlexception).  \n  \n## See Also  \n [AtlThrow](http://msdn.microsoft.com/library/2bd111da-8170-488d-914a-c9bf6b6765f7)   \n [Class Overview](../../atl/atl-class-overview.md)\n"}