{"nodes":[{"pos":[12,60],"content":"Exceptions: Database Exceptions | Microsoft Docs","needQuote":false,"needEscape":true,"nodes":[{"content":"Exceptions: Database Exceptions | Microsoft Docs","pos":[0,48]}]},{"content":"Exceptions: Database Exceptions","pos":[850,881]},{"content":"This article explains how to handle database exceptions.","pos":[882,938]},{"content":"Most of the material in this article applies whether you are working with the MFC classes for Open Database Connectivity (ODBC) or the MFC classes for Data Access Objects (DAO).","pos":[939,1116]},{"content":"Material specific to one or the other model is explicitly marked.","pos":[1117,1182]},{"content":"Topics include:","pos":[1183,1198]},{"content":"Approaches to exception handling","pos":[1209,1241]},{"content":"A database exception-handling example","pos":[1294,1331]},{"pos":[1445,1477],"content":"Approaches to Exception Handling"},{"content":"The approach is the same whether you are working with DAO or ODBC.","pos":[1481,1547]},{"content":"You should always write exception handlers to handle exceptional conditions.","pos":[1554,1630]},{"content":"The most pragmatic approach to catching database exceptions is to test your application with exception scenarios.","pos":[1637,1750]},{"content":"Determine the likely exceptions that might occur for an operation in your code, and force the exception to occur.","pos":[1751,1864]},{"content":"Then examine the trace output to see what exception is thrown, or examine the returned error information in the debugger.","pos":[1865,1986]},{"content":"This lets you know which return codes you'll see for the exception scenarios you are using.","pos":[1987,2078]},{"content":"Error Codes Used for ODBC Exceptions","pos":[2088,2124]},{"content":"In addition to return codes defined by the framework, which have names of the form <bpt id=\"p1\">**</bpt>AFX_SQL_ERROR_XXX<ept id=\"p1\">**</ept>, some <bpt id=\"p2\">[</bpt>CDBExceptions<ept id=\"p2\">](../mfc/reference/cdbexception-class.md)</ept> are based on <bpt id=\"p3\">[</bpt>ODBC<ept id=\"p3\">](../data/odbc/odbc-basics.md)</ept> return codes.","pos":[2128,2357],"source":"In addition to return codes defined by the framework, which have names of the form **AFX_SQL_ERROR_XXX**, some [CDBExceptions](../mfc/reference/cdbexception-class.md) are based on [ODBC](../data/odbc/odbc-basics.md) return codes."},{"content":"The return codes for such exceptions have names of the form <bpt id=\"p1\">**</bpt>SQL_ERROR_XXX<ept id=\"p1\">**</ept>.","pos":[2358,2436],"source":" The return codes for such exceptions have names of the form **SQL_ERROR_XXX**."},{"content":"The return codes — both framework-defined and ODBC-defined — that the database classes can return are documented under the <bpt id=\"p1\">[</bpt>m_nRetCode<ept id=\"p1\">](../mfc/reference/cdbexception-class.md#cdbexception__m_nretcode)</ept> data member of class <ph id=\"ph1\">`CDBException`</ph>.","pos":[2443,2680],"source":"The return codes — both framework-defined and ODBC-defined — that the database classes can return are documented under the [m_nRetCode](../mfc/reference/cdbexception-class.md#cdbexception__m_nretcode) data member of class `CDBException`."},{"content":"Additional information about return codes defined by ODBC is available in the ODBC SDK <bpt id=\"p1\">*</bpt>Programmer's Reference<ept id=\"p1\">*</ept> in the MSDN Library.","pos":[2681,2813],"source":" Additional information about return codes defined by ODBC is available in the ODBC SDK *Programmer's Reference* in the MSDN Library."},{"content":"Error Codes Used for DAO Exceptions","pos":[2823,2858]},{"content":"For DAO exceptions, more information is typically available.","pos":[2862,2922]},{"content":"You can access error information through three data members of a caught <bpt id=\"p1\">[</bpt>CDaoException<ept id=\"p1\">](../mfc/reference/cdaoexception-class.md)</ept> object:","pos":[2923,3059],"source":" You can access error information through three data members of a caught [CDaoException](../mfc/reference/cdaoexception-class.md) object:"},{"pos":[3069,3347],"content":"<bpt id=\"p1\">[</bpt>m_pErrorInfo<ept id=\"p1\">](../mfc/reference/cdaoexception-class.md#cdaoexception__m_perrorinfo)</ept> contains a pointer to a <bpt id=\"p2\">[</bpt>CDaoErrorInfo<ept id=\"p2\">](../mfc/reference/cdaoerrorinfo-structure.md)</ept> object that encapsulates error information in DAO's collection of error objects associated with the database.","source":"[m_pErrorInfo](../mfc/reference/cdaoexception-class.md#cdaoexception__m_perrorinfo) contains a pointer to a [CDaoErrorInfo](../mfc/reference/cdaoerrorinfo-structure.md) object that encapsulates error information in DAO's collection of error objects associated with the database."},{"content":"<bpt id=\"p1\">[</bpt>m_nAfxDaoError<ept id=\"p1\">](../mfc/reference/cdaoexception-class.md#cdaoexception__m_nafxdaoerror)</ept> contains an extended error code from the MFC DAO classes.","pos":[3357,3502],"source":"[m_nAfxDaoError](../mfc/reference/cdaoexception-class.md#cdaoexception__m_nafxdaoerror) contains an extended error code from the MFC DAO classes."},{"content":"These error codes, which have names of the form <bpt id=\"p1\">**</bpt>AFX_DAO_ERROR_XXX<ept id=\"p1\">**</ept>, are documented under the data member in <ph id=\"ph1\">`CDaoException`</ph>.","pos":[3503,3630],"source":" These error codes, which have names of the form **AFX_DAO_ERROR_XXX**, are documented under the data member in `CDaoException`."},{"content":"<bpt id=\"p1\">[</bpt>m_scode<ept id=\"p1\">](../mfc/reference/cdaoexception-class.md#cdaoexception__m_scode)</ept> contains an OLE <ph id=\"ph1\">`SCODE`</ph> from DAO, if applicable.","pos":[3640,3762],"source":"[m_scode](../mfc/reference/cdaoexception-class.md#cdaoexception__m_scode) contains an OLE `SCODE` from DAO, if applicable."},{"content":"You'll seldom need to work with this error code, however.","pos":[3763,3820]},{"content":"Usually more information is available in the other two data members.","pos":[3821,3889]},{"content":"See the data member for more about <ph id=\"ph1\">`SCODE`</ph> values.","pos":[3890,3940],"source":" See the data member for more about `SCODE` values."},{"pos":[3947,4127],"content":"Additional information about DAO errors, the DAO Error object type, and the DAO Errors collection is available under class <bpt id=\"p1\">[</bpt>CDaoException<ept id=\"p1\">](../mfc/reference/cdaoexception-class.md)</ept>.","source":"Additional information about DAO errors, the DAO Error object type, and the DAO Errors collection is available under class [CDaoException](../mfc/reference/cdaoexception-class.md)."},{"pos":[4199,4236],"content":"A Database Exception-Handling Example"},{"content":"The following example attempts to construct a <bpt id=\"p1\">[</bpt>CRecordset<ept id=\"p1\">](../mfc/reference/crecordset-class.md)</ept>-derived object on the heap with the <bpt id=\"p2\">**</bpt>new<ept id=\"p2\">**</ept> operator, and then open the recordset (for an ODBC data source).","pos":[4240,4445],"source":"The following example attempts to construct a [CRecordset](../mfc/reference/crecordset-class.md)-derived object on the heap with the **new** operator, and then open the recordset (for an ODBC data source)."},{"content":"For a similar example for the DAO classes, see \"DAO Exception Example\" below.","pos":[4446,4523]},{"content":"ODBC Exception Example","pos":[4533,4555]},{"content":"The <bpt id=\"p1\">[</bpt>Open<ept id=\"p1\">](../mfc/reference/crecordset-class.md#crecordset__open)</ept> member function could throw an exception (of type <bpt id=\"p2\">[</bpt>CDBException<ept id=\"p2\">](../mfc/reference/cdbexception-class.md)</ept> for the ODBC classes), so this code brackets the <bpt id=\"p3\">**</bpt>Open<ept id=\"p3\">**</ept> call with a <bpt id=\"p4\">**</bpt>try<ept id=\"p4\">**</ept> block.","pos":[4559,4814],"source":"The [Open](../mfc/reference/crecordset-class.md#crecordset__open) member function could throw an exception (of type [CDBException](../mfc/reference/cdbexception-class.md) for the ODBC classes), so this code brackets the **Open** call with a **try** block."},{"content":"The subsequent <bpt id=\"p1\">**</bpt>catch<ept id=\"p1\">**</ept> block will catch a <ph id=\"ph1\">`CDBException`</ph>.","pos":[4815,4874],"source":" The subsequent **catch** block will catch a `CDBException`."},{"content":"You could examine the exception object itself, called <ph id=\"ph1\">`e`</ph>, but in this case it is enough to know that the attempt to create a recordset has failed.","pos":[4875,5022],"source":" You could examine the exception object itself, called `e`, but in this case it is enough to know that the attempt to create a recordset has failed."},{"content":"The <bpt id=\"p1\">**</bpt>catch<ept id=\"p1\">**</ept> block displays a message box and cleans up by deleting the recordset object.","pos":[5023,5113],"source":" The **catch** block displays a message box and cleans up by deleting the recordset object."},{"pos":[5131,5149],"content":"NVC_MFCDatabase#36"},{"content":"DAO Exception Example","pos":[5222,5243]},{"content":"The DAO example is similar to the example for ODBC, but you can typically retrieve more kinds of information.","pos":[5247,5356]},{"content":"The following code also attempts to open a recordset.","pos":[5357,5410]},{"content":"If that attempt throws an exception, you can examine a data member of the exception object for error information.","pos":[5411,5524]},{"content":"As with the previous ODBC example, it is probably enough to know that the attempt to create a recordset failed.","pos":[5525,5636]},{"pos":[5654,5672],"content":"NVC_MFCDatabase#37"},{"content":"This code gets an error message string from the <bpt id=\"p1\">[</bpt>m_pErrorInfo<ept id=\"p1\">](../mfc/reference/cdaoexception-class.md#cdaoexception__m_perrorinfo)</ept> member of the exception object.","pos":[5742,5905],"source":"This code gets an error message string from the [m_pErrorInfo](../mfc/reference/cdaoexception-class.md#cdaoexception__m_perrorinfo) member of the exception object."},{"content":"MFC fills this member when it throws the exception.","pos":[5906,5957]},{"pos":[5964,6178],"content":"For a discussion of the error information returned by a <ph id=\"ph1\">`CDaoException`</ph> object, see classes <bpt id=\"p1\">[</bpt>CDaoException<ept id=\"p1\">](../mfc/reference/cdaoexception-class.md)</ept> and <bpt id=\"p2\">[</bpt>CDaoErrorInfo<ept id=\"p2\">](../mfc/reference/cdaoerrorinfo-structure.md)</ept>.","source":"For a discussion of the error information returned by a `CDaoException` object, see classes [CDaoException](../mfc/reference/cdaoexception-class.md) and [CDaoErrorInfo](../mfc/reference/cdaoerrorinfo-structure.md)."},{"content":"When you are working with Microsoft Jet (.mdb) databases, and in most cases when you are working with ODBC, there will be only one error object.","pos":[6185,6329]},{"content":"In the rare case when you are using an ODBC data source and there are multiple errors, you can loop through DAO's Errors collection based on the number of errors returned by <bpt id=\"p1\">[</bpt>CDaoException::GetErrorCount<ept id=\"p1\">](../mfc/reference/cdaoexception-class.md#cdaoexception__geterrorcount)</ept>.","pos":[6330,6605],"source":" In the rare case when you are using an ODBC data source and there are multiple errors, you can loop through DAO's Errors collection based on the number of errors returned by [CDaoException::GetErrorCount](../mfc/reference/cdaoexception-class.md#cdaoexception__geterrorcount)."},{"content":"Each time through the loop, call <bpt id=\"p1\">[</bpt>CDaoException::GetErrorInfo<ept id=\"p1\">](../mfc/reference/cdaoexception-class.md#cdaoexception__geterrorinfo)</ept> to refill the <ph id=\"ph1\">`m_pErrorInfo`</ph> data member.","pos":[6606,6779],"source":" Each time through the loop, call [CDaoException::GetErrorInfo](../mfc/reference/cdaoexception-class.md#cdaoexception__geterrorinfo) to refill the `m_pErrorInfo` data member."},{"content":"See Also","pos":[6788,6796]},{"content":"Exception Handling","pos":[6801,6819]}],"content":"---\ntitle: \"Exceptions: Database Exceptions | Microsoft Docs\"\nms.custom: \"\"\nms.date: \"11/04/2016\"\nms.reviewer: \"\"\nms.suite: \"\"\nms.technology: \n  - \"devlang-cpp\"\nms.tgt_pltfrm: \"\"\nms.topic: \"article\"\ndev_langs: \n  - \"C++\"\nhelpviewer_keywords: \n  - \"DAO [C++], exceptions\"\n  - \"exceptions [C++], database\"\n  - \"exception handling [C++], databases\"\n  - \"ODBC exceptions [C++]\"\n  - \"ODBC [C++], exceptions\"\n  - \"database exceptions [C++]\"\n  - \"databases [C++], exception handling\"\n  - \"error codes [C++], database exception handling\"\nms.assetid: 28daf260-f824-4be6-aecc-1f859e6dec26\ncaps.latest.revision: 10\nauthor: \"mikeblome\"\nms.author: \"mblome\"\nmanager: \"ghogen\"\ntranslation.priority.ht: \n  - \"cs-cz\"\n  - \"de-de\"\n  - \"es-es\"\n  - \"fr-fr\"\n  - \"it-it\"\n  - \"ja-jp\"\n  - \"ko-kr\"\n  - \"pl-pl\"\n  - \"pt-br\"\n  - \"ru-ru\"\n  - \"tr-tr\"\n  - \"zh-cn\"\n  - \"zh-tw\"\n---\n# Exceptions: Database Exceptions\nThis article explains how to handle database exceptions. Most of the material in this article applies whether you are working with the MFC classes for Open Database Connectivity (ODBC) or the MFC classes for Data Access Objects (DAO). Material specific to one or the other model is explicitly marked. Topics include:  \n  \n-   [Approaches to exception handling](#_core_approaches_to_exception_handling)  \n  \n-   [A database exception-handling example](#_core_a_database_exception.2d.handling_example)  \n  \n##  <a name=\"_core_approaches_to_exception_handling\"></a> Approaches to Exception Handling  \n The approach is the same whether you are working with DAO or ODBC.  \n  \n You should always write exception handlers to handle exceptional conditions.  \n  \n The most pragmatic approach to catching database exceptions is to test your application with exception scenarios. Determine the likely exceptions that might occur for an operation in your code, and force the exception to occur. Then examine the trace output to see what exception is thrown, or examine the returned error information in the debugger. This lets you know which return codes you'll see for the exception scenarios you are using.  \n  \n### Error Codes Used for ODBC Exceptions  \n In addition to return codes defined by the framework, which have names of the form **AFX_SQL_ERROR_XXX**, some [CDBExceptions](../mfc/reference/cdbexception-class.md) are based on [ODBC](../data/odbc/odbc-basics.md) return codes. The return codes for such exceptions have names of the form **SQL_ERROR_XXX**.  \n  \n The return codes — both framework-defined and ODBC-defined — that the database classes can return are documented under the [m_nRetCode](../mfc/reference/cdbexception-class.md#cdbexception__m_nretcode) data member of class `CDBException`. Additional information about return codes defined by ODBC is available in the ODBC SDK *Programmer's Reference* in the MSDN Library.  \n  \n### Error Codes Used for DAO Exceptions  \n For DAO exceptions, more information is typically available. You can access error information through three data members of a caught [CDaoException](../mfc/reference/cdaoexception-class.md) object:  \n  \n-   [m_pErrorInfo](../mfc/reference/cdaoexception-class.md#cdaoexception__m_perrorinfo) contains a pointer to a [CDaoErrorInfo](../mfc/reference/cdaoerrorinfo-structure.md) object that encapsulates error information in DAO's collection of error objects associated with the database.  \n  \n-   [m_nAfxDaoError](../mfc/reference/cdaoexception-class.md#cdaoexception__m_nafxdaoerror) contains an extended error code from the MFC DAO classes. These error codes, which have names of the form **AFX_DAO_ERROR_XXX**, are documented under the data member in `CDaoException`.  \n  \n-   [m_scode](../mfc/reference/cdaoexception-class.md#cdaoexception__m_scode) contains an OLE `SCODE` from DAO, if applicable. You'll seldom need to work with this error code, however. Usually more information is available in the other two data members. See the data member for more about `SCODE` values.  \n  \n Additional information about DAO errors, the DAO Error object type, and the DAO Errors collection is available under class [CDaoException](../mfc/reference/cdaoexception-class.md).  \n  \n##  <a name=\"_core_a_database_exception.2d.handling_example\"></a> A Database Exception-Handling Example  \n The following example attempts to construct a [CRecordset](../mfc/reference/crecordset-class.md)-derived object on the heap with the **new** operator, and then open the recordset (for an ODBC data source). For a similar example for the DAO classes, see \"DAO Exception Example\" below.  \n  \n### ODBC Exception Example  \n The [Open](../mfc/reference/crecordset-class.md#crecordset__open) member function could throw an exception (of type [CDBException](../mfc/reference/cdbexception-class.md) for the ODBC classes), so this code brackets the **Open** call with a **try** block. The subsequent **catch** block will catch a `CDBException`. You could examine the exception object itself, called `e`, but in this case it is enough to know that the attempt to create a recordset has failed. The **catch** block displays a message box and cleans up by deleting the recordset object.  \n  \n [!code-cpp[NVC_MFCDatabase#36](../mfc/codesnippet/cpp/exceptions-database-exceptions_1.cpp)]  \n  \n### DAO Exception Example  \n The DAO example is similar to the example for ODBC, but you can typically retrieve more kinds of information. The following code also attempts to open a recordset. If that attempt throws an exception, you can examine a data member of the exception object for error information. As with the previous ODBC example, it is probably enough to know that the attempt to create a recordset failed.  \n  \n [!code-cpp[NVC_MFCDatabase#37](../mfc/codesnippet/cpp/exceptions-database-exceptions_2.cpp)]  \n  \n This code gets an error message string from the [m_pErrorInfo](../mfc/reference/cdaoexception-class.md#cdaoexception__m_perrorinfo) member of the exception object. MFC fills this member when it throws the exception.  \n  \n For a discussion of the error information returned by a `CDaoException` object, see classes [CDaoException](../mfc/reference/cdaoexception-class.md) and [CDaoErrorInfo](../mfc/reference/cdaoerrorinfo-structure.md).  \n  \n When you are working with Microsoft Jet (.mdb) databases, and in most cases when you are working with ODBC, there will be only one error object. In the rare case when you are using an ODBC data source and there are multiple errors, you can loop through DAO's Errors collection based on the number of errors returned by [CDaoException::GetErrorCount](../mfc/reference/cdaoexception-class.md#cdaoexception__geterrorcount). Each time through the loop, call [CDaoException::GetErrorInfo](../mfc/reference/cdaoexception-class.md#cdaoexception__geterrorinfo) to refill the `m_pErrorInfo` data member.  \n  \n## See Also  \n [Exception Handling](../mfc/exception-handling-in-mfc.md)\n\n"}