{"nodes":[{"pos":[12,50],"content":"underflow_error Class | Microsoft Docs","needQuote":false,"needEscape":true,"nodes":[{"content":"underflow_error Class | Microsoft Docs","pos":[0,38]}]},{"pos":[707,728],"content":"underflow_error Class","linkify":"underflow_error Class","nodes":[{"content":"underflow_error Class","pos":[0,21]}]},{"content":"The class serves as the base class for all exceptions thrown to report an arithmetic underflow.","pos":[729,824]},{"pos":[833,839],"content":"Syntax","linkify":"Syntax","nodes":[{"content":"Syntax","pos":[0,6]}]},{"pos":[1033,1040],"content":"Remarks","linkify":"Remarks","nodes":[{"content":"Remarks","pos":[0,7]}]},{"pos":[1044,1209],"content":"The value returned by <bpt id=\"p1\">[</bpt>what<ept id=\"p1\">](../standard-library/exception-class.md)</ept> is a copy of <bpt id=\"p2\">**</bpt>message<ept id=\"p2\">**</ept><ph id=\"ph1\">`.`</ph><bpt id=\"p3\">[</bpt>data<ept id=\"p3\">](../standard-library/basic-string-class.md#basic_string__data)</ept>.","source":"The value returned by [what](../standard-library/exception-class.md) is a copy of **message**`.`[data](../standard-library/basic-string-class.md#basic_string__data)."},{"pos":[1218,1225],"content":"Example","linkify":"Example","nodes":[{"content":"Example","pos":[0,7]}]},{"pos":[1717,1729],"content":"Requirements","linkify":"Requirements","nodes":[{"content":"Requirements","pos":[0,12]}]},{"pos":[1733,1757],"content":"<bpt id=\"p1\">**</bpt>Header:<ept id=\"p1\">**</ept> <ph id=\"ph1\">\\&lt;</ph>stdexcept&gt;","source":"**Header:** \\<stdexcept>"},{"pos":[1764,1782],"content":"<bpt id=\"p1\">**</bpt>Namespace:<ept id=\"p1\">**</ept> std","source":"**Namespace:** std"},{"pos":[1791,1799],"content":"See Also","linkify":"See Also","nodes":[{"content":"See Also","pos":[0,8]}]},{"content":"<bpt id=\"p1\">[</bpt><ph id=\"ph1\">\\&lt;</ph>stdexcept&gt; Members<ept id=\"p1\">](http://msdn.microsoft.com/en-us/7b6b0a73-916e-44aa-9a3f-f5b6b3ce98e6)</ept><ph id=\"ph2\"> </ph>","pos":[1803,1896],"source":"[\\<stdexcept> Members](http://msdn.microsoft.com/en-us/7b6b0a73-916e-44aa-9a3f-f5b6b3ce98e6) "},{"content":"<bpt id=\"p1\"> [</bpt>runtime_error Class<ept id=\"p1\">](../standard-library/runtime-error-class.md)</ept><ph id=\"ph1\"> </ph>","pos":[1899,1966],"source":" [runtime_error Class](../standard-library/runtime-error-class.md) "},{"content":"<bpt id=\"p1\"> [</bpt>Thread Safety in the C++ Standard Library<ept id=\"p1\">](../standard-library/thread-safety-in-the-cpp-standard-library.md)</ept>","pos":[1969,2079],"source":" [Thread Safety in the C++ Standard Library](../standard-library/thread-safety-in-the-cpp-standard-library.md)"}],"content":"---\ntitle: \"underflow_error Class | Microsoft Docs\"\nms.custom: \"\"\nms.date: \"11/04/2016\"\nms.reviewer: \"\"\nms.suite: \"\"\nms.technology: \n  - \"devlang-cpp\"\nms.tgt_pltfrm: \"\"\nms.topic: \"article\"\nf1_keywords: \n  - \"stdexcept/std::underflow_error\"\n  - \"underflow_error\"\n  - \"std.underflow_error\"\n  - \"std::underflow_error\"\ndev_langs: \n  - \"C++\"\nhelpviewer_keywords: \n  - \"underflow_error class\"\nms.assetid: d632f1f9-9c6c-4954-b96b-03041bfab22d\ncaps.latest.revision: 20\nauthor: \"corob-msft\"\nms.author: \"corob\"\nmanager: \"ghogen\"\ntranslation.priority.ht: \n  - \"cs-cz\"\n  - \"de-de\"\n  - \"es-es\"\n  - \"fr-fr\"\n  - \"it-it\"\n  - \"ja-jp\"\n  - \"ko-kr\"\n  - \"pl-pl\"\n  - \"pt-br\"\n  - \"ru-ru\"\n  - \"tr-tr\"\n  - \"zh-cn\"\n  - \"zh-tw\"\n---\n# underflow_error Class\nThe class serves as the base class for all exceptions thrown to report an arithmetic underflow.  \n  \n## Syntax  \n  \n```  \nclass underflow_error : public runtime_error {  \npublic:  \n    explicit underflow_error(const string& message);\n\n    explicit underflow_error(const char *message);\n\n};  \n```  \n  \n## Remarks  \n The value returned by [what](../standard-library/exception-class.md) is a copy of **message**`.`[data](../standard-library/basic-string-class.md#basic_string__data).  \n  \n## Example  \n  \n```cpp  \n// underflow_error.cpp  \n// compile with: /EHsc /GR  \n#include <iostream>  \n  \nusing namespace std;  \n  \nint main( )  \n{  \n   try   \n   {  \n      throw underflow_error( \"The number's a bit small, captain!\" );  \n   }  \n   catch ( exception &e ) {  \n      cerr << \"Caught: \" << e.what( ) << endl;  \n      cerr << \"Type: \" << typeid( e ).name( ) << endl;  \n   };  \n}  \n\\* Output:   \nCaught: The number's a bit small, captain!  \nType: class std::underflow_error  \n*\\  \n```  \n  \n## Requirements  \n **Header:** \\<stdexcept>  \n  \n **Namespace:** std  \n  \n## See Also  \n [\\<stdexcept> Members](http://msdn.microsoft.com/en-us/7b6b0a73-916e-44aa-9a3f-f5b6b3ce98e6)   \n [runtime_error Class](../standard-library/runtime-error-class.md)   \n [Thread Safety in the C++ Standard Library](../standard-library/thread-safety-in-the-cpp-standard-library.md)\n\n"}